USE [master]
GO

/****** Object:  Database [HotelResevation]    Script Date: 2017-10-22 9:11:12 PM ******/
CREATE DATABASE [HotelResevation]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HotelResevation', FILENAME = N'.\HotelResevation.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HotelResevation_log', FILENAME = N'.\HotelResevation_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [HotelResevation] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HotelResevation].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HotelResevation] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HotelResevation] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HotelResevation] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HotelResevation] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HotelResevation] SET ARITHABORT OFF 
GO

ALTER DATABASE [HotelResevation] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HotelResevation] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HotelResevation] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HotelResevation] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HotelResevation] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HotelResevation] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HotelResevation] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HotelResevation] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HotelResevation] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HotelResevation] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HotelResevation] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HotelResevation] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HotelResevation] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HotelResevation] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HotelResevation] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HotelResevation] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HotelResevation] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HotelResevation] SET RECOVERY FULL 
GO

ALTER DATABASE [HotelResevation] SET  MULTI_USER 
GO

ALTER DATABASE [HotelResevation] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HotelResevation] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HotelResevation] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HotelResevation] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HotelResevation] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HotelResevation] SET QUERY_STORE = OFF
GO

USE [HotelResevation]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [HotelResevation] SET  READ_WRITE 
GO

